name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and verify with Maven
      run: mvn -B verify --file pom.xml

    - name: Cache dependency-check
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository/org/owasp/dependency-check-data
        key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-

    - name: Check for dependency vulnerabilities
      run: |
        mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=11

    - name: Check for outdated dependencies
      run: |
        mvn versions:display-dependency-updates

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: target/*.jar
